// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivePresetID() {
  return window['go']['main']['App']['ActivePresetID']();
}

export function CancelParse() {
  return window['go']['main']['App']['CancelParse']();
}

export function ChooseReplay() {
  return window['go']['main']['App']['ChooseReplay']();
}

export function CurrentPreset() {
  return window['go']['main']['App']['CurrentPreset']();
}

export function EmitResult() {
  return window['go']['main']['App']['EmitResult']();
}

export function EvalPreview(arg1) {
  return window['go']['main']['App']['EvalPreview'](arg1);
}

export function ExportPreset(arg1, arg2) {
  return window['go']['main']['App']['ExportPreset'](arg1, arg2);
}

export function ExportPresetDialog(arg1) {
  return window['go']['main']['App']['ExportPresetDialog'](arg1);
}

export function GetParserURL() {
  return window['go']['main']['App']['GetParserURL']();
}

export function HeroImageURL(arg1) {
  return window['go']['main']['App']['HeroImageURL'](arg1);
}

export function ImportPreset(arg1) {
  return window['go']['main']['App']['ImportPreset'](arg1);
}

export function ImportPresetDialog() {
  return window['go']['main']['App']['ImportPresetDialog']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ParseReplay(arg1) {
  return window['go']['main']['App']['ParseReplay'](arg1);
}

export function Recompute() {
  return window['go']['main']['App']['Recompute']();
}

export function RemovePreset(arg1) {
  return window['go']['main']['App']['RemovePreset'](arg1);
}

export function SetActivePreset(arg1) {
  return window['go']['main']['App']['SetActivePreset'](arg1);
}

export function SetParserURL(arg1) {
  return window['go']['main']['App']['SetParserURL'](arg1);
}

export function UpsertPreset(arg1) {
  return window['go']['main']['App']['UpsertPreset'](arg1);
}
